/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ParcelCompact() {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lasttry4-transformed.glb')
  return (
    <group ref={group}  dispose={null} scale={1} position={[0, -4, -2]}>
      <mesh geometry={nodes.SynthLandSCape002_SynthLandSCape001.geometry} material={materials['Material.004']} position={[0, 159.09, 54.14]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/lasttry4-transformed.glb')
